name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  # Job para ejecutar las pruebas unitarias
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: pytest tests/

  # Job para ejecutar las pruebas de integración
  integration-tests:
    runs-on: ubuntu-latest
    needs: test  # Se ejecuta después del job de pruebas unitarias
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest httpx  

      - name: Run Integration Tests
        run: pytest tests/integration/  # Ejecuta las pruebas de integración en la carpeta específica

  # Job para análisis de código estático con SonarQube/SonarCloud
  sonar:
    runs-on: ubuntu-latest
    needs: integration-tests  # Se ejecuta después del job de pruebas de integración
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Java (requisito para SonarQube)
        run: sudo apt-get install -y openjdk-11-jdk

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=tarea1-cc3s2
            -Dsonar.organization=renato200419
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
